"""added_model_url_and_error_to_scanjob

Revision ID: 09fa697858c6
Revises: 1a5c58421ec4
Create Date: 2026-03-05 17:10:22.714098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09fa697858c6'
down_revision: Union[str, Sequence[str], None] = '1a5c58421ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_jobs', sa.Column('model_url', sa.String(), nullable=True))
    op.alter_column('scan_jobs', 'error_message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_jobs', 'error_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('scan_jobs', 'model_url')
    # ### end Alembic commands ###
