"""added_initializing_uploading_to_jobstatus

Revision ID: 150f60276b47
Revises: 09fa697858c6
Create Date: 2026-03-05 17:56:25.016069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '150f60276b47'
down_revision: Union[str, Sequence[str], None] = '09fa697858c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT") # Need to commit current transaction or run as non-transactional
    op.execute("ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'initializing'")
    op.execute("ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'uploading'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
