"""added_scan_images_table

Revision ID: 1a5c58421ec4
Revises: 5814c67855b0
Create Date: 2026-03-05 15:13:38.546301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5c58421ec4'
down_revision: Union[str, Sequence[str], None] = '5814c67855b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('is_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['scan_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('scan_jobs', sa.Column('reference_scale', sa.String(), nullable=True))
    
    # Create the Enum type first
    jobstatus_enum = sa.Enum('pending', 'processing', 'completed', 'failed', name='jobstatus')
    jobstatus_enum.create(op.get_bind(), checkfirst=True)
    
    # Then alter the column using the USING clause to cast existing strings to the new Enum
    op.execute("ALTER TABLE scan_jobs ALTER COLUMN status TYPE jobstatus USING status::jobstatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE scan_jobs ALTER COLUMN status TYPE varchar USING status::varchar")
    jobstatus_enum = sa.Enum('pending', 'processing', 'completed', 'failed', name='jobstatus')
    jobstatus_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_column('scan_jobs', 'reference_scale')
    op.drop_table('scan_images')
    # ### end Alembic commands ###
