"""added_warnings_column

Revision ID: 40ed42d695fa
Revises: 48aee3ba041d
Create Date: 2026-03-06 07:52:31.150406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ed42d695fa'
down_revision: Union[str, Sequence[str], None] = '48aee3ba041d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 🛡️ MANUAL FIX: PostgreSQL requires creating the Enum type before using it in alter_column
    referencetype = sa.Enum('regular', 'coin', name='referencetype')
    referencetype.create(op.get_bind(), checkfirst=True)

    op.alter_column('scan_images', 'is_reference',
               existing_type=sa.VARCHAR(),
               type_=referencetype,
               existing_nullable=True,
               postgresql_using="(CASE is_reference WHEN 'false' THEN 'regular' WHEN 'coin' THEN 'coin' ELSE 'regular' END)::referencetype")
    op.add_column('scan_jobs', sa.Column('warnings', sa.Text(), nullable=True))
    op.create_index(op.f('ix_scan_jobs_created_at'), 'scan_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_scan_jobs_project_name'), 'scan_jobs', ['project_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_jobs_project_name'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_created_at'), table_name='scan_jobs')
    op.drop_column('scan_jobs', 'warnings')
    op.alter_column('scan_images', 'is_reference',
               existing_type=sa.Enum('regular', 'coin', name='referencetype'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    
    # 🛡️ MANUAL FIX: Clean up the Enum type
    sa.Enum('regular', 'coin', name='referencetype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
