"""added project_name to scanjob

Revision ID: 48aee3ba041d
Revises: 900a2513b481
Create Date: 2026-03-06 12:01:17.165769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48aee3ba041d'
down_revision: Union[str, Sequence[str], None] = '900a2513b481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_jobs', sa.Column('project_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_jobs', 'project_name')
    # ### end Alembic commands ###
