"""added_cancelled_status

Revision ID: 900a2513b481
Revises: 150f60276b47
Create Date: 2026-03-05 18:45:33.099450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '900a2513b481'
down_revision: Union[str, Sequence[str], None] = '150f60276b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Postgres doesn't allow adding enum values inside a transaction easily.
    # We use execute() to run the ALTER TYPE command.
    # Note: This might fail if run inside a transaction depending on the Postgres version.
    op.execute("COMMIT") # Break out of the transaction if Postgres < 12 requires it
    op.execute("ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'cancelled'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
